mod discord_icon;
mod github_icon;
mod linkedin_icon;
mod location_icon;
mod logo_rust_page;
mod next;
mod shuttle_icon;
mod telegram_icon;
mod twitter_icon;
mod web_icon;

pub use discord_icon::*;
pub use github_icon::*;
pub use linkedin_icon::*;
pub use location_icon::*;
pub use logo_rust_page::*;
pub use next::*;
pub use shuttle_icon::*;
pub use telegram_icon::*;
pub use twitter_icon::*;
pub use web_icon::*;
